/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";
export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/welcome.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.welcome.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            geometry={nodes.Ch23_Belt.geometry}
            material={materials.Ch23_body}
            skeleton={nodes.Ch23_Belt.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Ch23_Body.geometry}
            material={materials.Ch23_body}
            skeleton={nodes.Ch23_Body.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Ch23_Eyelashes.geometry}
            material={materials.Ch23_hair}
            skeleton={nodes.Ch23_Eyelashes.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Ch23_Hair.geometry}
            material={materials.Ch23_hair}
            skeleton={nodes.Ch23_Hair.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Ch23_Pants.geometry}
            material={materials.Ch23_body}
            skeleton={nodes.Ch23_Pants.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Ch23_Shirt.geometry}
            material={materials.Ch23_body}
            skeleton={nodes.Ch23_Shirt.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Ch23_Shoes.geometry}
            material={materials.Ch23_body}
            skeleton={nodes.Ch23_Shoes.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Ch23_Suit.geometry}
            material={materials.Ch23_body}
            skeleton={nodes.Ch23_Suit.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/welcome.glb");
